export const siteConfig = {
  name: "QOL Clinical",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.qolclinical.com",
  title: "QOL Clinical — Acompañamiento clínico integral",
  description:
    "QOL Clinical es un acompañante clínico integral especializado en el manejo de condiciones crónicas y agudas. Nuestro equipo multidisciplinario evalúa tu estado de salud completo, revisa tus tratamientos y construye contigo un plan jerarquizado, claro y sostenible.",
  keywords: [
    "condiciones crónicas",
    "condiciones agudas",
    "teleconsulta",
    "acompañamiento clínico",
    "acompañamiento farmacéutico",
    "segunda opinión médica",
    "reumatología",
    "neurología",
    "oncología",
    "cardiología",
    "endocrinología",
    "enfermedades raras",
    "infertilidad",
    "medicina estética",
    "Costa Rica",
    "San José",
    "clínica integral",
    "plan de salud",
    "seguimiento médico",
    "manejo crónico",
  ],
  phone: "+50686036047",
  address: {
    streetAddress: "San Pedro",
    addressLocality: "San José",
    addressRegion: "San José",
    addressCountry: "CR",
  },
  locale: "es_CR",
  themeColor: "#28574E",
  ogImage: "/qol-social.png",
  googleVerification: "google034f4af09b834679",
  doctor: {
    name: "Dr. Javier León",
    jobTitle: "Director Médico",
  },
} as const;
