export const siteConfig = {
  name: "QOL Clinical",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.qolclinical.com",
  title: "QOL Clinical | Acompañamiento Clínico Integral en Costa Rica",
  description:
    "Teleconsulta y seguimiento clínico para condiciones crónicas en Costa Rica. Tu equipo construye contigo un plan de salud claro y sostenible.",
  keywords: [
    "condiciones crónicas",
    "condiciones agudas",
    "teleconsulta",
    "acompañamiento clínico",
    "acompañamiento farmacéutico",
    "segunda opinión médica",
    "reumatología",
    "neurología",
    "oncología",
    "cardiología",
    "endocrinología",
    "enfermedades raras",
    "infertilidad",
    "medicina estética",
    "Costa Rica",
    "San José",
    "clínica integral",
    "plan de salud",
    "seguimiento médico",
    "manejo crónico",
  ],
  phone: "+50686036047",
  address: {
    streetAddress: "San Pedro",
    addressLocality: "San José",
    addressRegion: "San José",
    addressCountry: "CR",
  },
  locale: "es_CR",
  themeColor: "#28574E",
  ogImage: "/qol-clinical-social.png",
  googleVerification: "google034f4af09b834679",
  doctor: {
    name: "Dr. Javier León",
    jobTitle: "Director Médico",
  },
} as const;
